### PR TITLE
Added support for disk usage Jenkins plugin

### PR DESCRIPTION
**Pull request by Heldroe**
Before:
disk1_before
disk2_before

After:
disk1_after
disk2_after

### CODE REVIEW

**Comment by afonsof** [comment]
Don't you think this icon is better? It's material design oficial
image

**Comment by Heldroe** [comment]
This one seems to be for mobile/internet data usage, maybe the storage one (from official) fits better:
storage

It's the one used for disk usage on Android

**Comment by afonsof** [comment]
I agree :smile:. Could you replace it?

**Comment by Heldroe** [comment]
Ok I'm on it

**Comment by Heldroe** [comment]
disk2
disk22

Looks fine

**Comment by afonsof** [comment]
Excellent!

**Pull request merged**
