### PR TITLE
Better visibility for links on console output.

### PR DESCRIPTION
**Pull request by mrchief**
Basically turn this:

image

into this:

image

### CODE REVIEW

**Comment by afonsof** [comment]
In my case the problem does not happen, look:
image
Are you using any plugin that might be changing the color of ```pre``` links?

Anyway, I guess we can include that new style but I couldn't find the ```@color-link-on-black``` variable definition. Did you forget to commit it?

**Comment by afonsof** [comment]
This problem is happening cause you have modified the theme correct?

**Comment by mrchief** [comment]
> This problem is happening cause you have modified the theme correct?

Hadn't realize that until you pointed it out. You can leave this PR out then if you wish. I've added the missing variable to the PR anyway.

**Comment by mrchief** [comment]
Also, do you see the hand icon on the links? It doesn't show for me (on console output mainly).

**Comment by afonsof** [comment]
Ouch, I didn't merge it. Unfortunately you pushed the same commits in the another pull request you made: Better buttons #18. It this one was merged automatically. But no problem.

Furthermore, I don't see the hand icon in console output either.

**Comment by mrchief** [comment]
I don't know why it showed 4 commits in the other one. I branched from master which shouldn't have those other commits. Not sure what happened.

This will fix the cursor:

```
pre {
  a, a:hover, a:visited, a:link {
    cursor: pointer;  
  }
}
```

**Pull request merged**
